### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by drybjed** [djangoxv/awx_debian#1]
What's the license of this project? I see that in the `meta/main.yml` you set the `license` field to `GPLv3`, however that's not good enough. If it is indeed GPLv3, you need to include the `LICENSE` file with the apropriate contents.

**Comment by djangoxv** [comment]
Agreed... thanks for bringing it to my attention

**Comment by djangoxv** [comment]
Ok - this is fixed in 8c00eda
